name: continuous-integration
on: push

jobs:
  test:
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v2
      - name: Set up HashLink
        uses: haxefoundation/setup-hashlink@master
        with:
          version: latest
      - name: Cache haxelib dependencies
        id: haxelib-cache
        uses: actions/cache@v4
        with:
          path: .haxelib
          key: haxe-${{runner.os}}-${{hashFiles('install.hxml')}}
      - name: Install dependencies
        if: steps.haxelib-cache.outputs.cache-hit != 'true'
        run: |
          haxelib newrepo
          haxelib state load install.hxml
      - name: Run tests
        run: haxe test.hxml
